# 1. Configurações de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/safehealth_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configurações do Hibernate (JPA)
# O "update" faz o Hibernate criar a tabela automaticamente baseado na nossa Entity
spring.jpa.hibernate.ddl-auto=update

# 3. Logs: Isso vai imprimir as querys SQL no console para vermos a mágica acontecer
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true